version: '3.8'

services:

  app:
    build:
      context: .
    container_name: mobilis-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mobilis
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - db
    networks:
      - mobilis-network

  db:
    image: postgres:15
    container_name: mobilis-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mobilis-network

volumes:
  postgres-data:


networks:
  mobilis-network:
    driver: bridge
