version: '3.8'

services:
 
  app:
    build:
      context: . 
    container_name: mobilis-app
    ports:
      - "8080:8080"  
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mobilis  
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  
    depends_on:
      - db  

  
  db:
    image: postgres:15
    container_name: mobilis-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mobilis
    ports:
      - "5432:5432"  
    volumes:
      - postgres-data:/var/lib/postgresql/data  

volumes:
  postgres-data:
